### ISSUE TITLE
AWS Lambda Functions Using Deprecated Runtimes

### ISSUE THREAD

**Issue by wgeiger-barrett** [medmunds/aws-cfn-ses-domain#18]
## Problem

AWS Trusted Advisor is identifying the custom Domain and Email lambda functions as deprecated.

## Solution

Update the runtime of the functions to be Python 3.9 or the latest LTS version.

## Compatibility

Unsure.

## System

* aws-cfn-ses-domain version: 0.3
* serverless version: 3.16.0

## Would you be willing to help?

Yes

**Comment by medmunds** [comment]
Thanks for reporting this. Updating to python3.9 now.

(Really wish there were some way to just set the Lambda runtime to "the latest" Python 3 version—there's nothing in here that cares about a specific Python version, as long as it's after 3.5.)
